const defaultTheme = require('tailwindcss/defaultTheme')

// [,'first', 'last', 'hover', 'focus', 'disabled', 'disabled']
// TODO: use variants.[pluginname] to optimize

module.exports = {
  variants: {
    accessibility: ['focus'],
    alignContent: [],
    alignItems: [],
    alignSelf: [],
    appearance: [],
    backgroundAttachment: [],
    backgroundColor: ['hover', 'focus', 'disabled'],
    backgroundPosition: [],
    backgroundRepeat: [],
    backgroundSize: [],
    borderCollapse: [],
    borderColor: ['hover', 'focus', 'disabled'],
    borderRadius: [],
    borderStyle: [],
    borderWidth: [],
    boxShadow: ['hover', 'focus', 'disabled'],
    boxSizing: [],
    cursor: [],
    display: [],
    fill: [],
    flex: [],
    flexDirection: [],
    flexGrow: [],
    flexShrink: [],
    flexWrap: [],
    float: [],
    clear: [],
    fontFamily: [],
    fontSize: [],
    fontSmoothing: [],
    fontStyle: [],
    fontWeight: ['hover', 'focus', 'disabled'],
    height: [],
    inset: [],
    justifyContent: [],
    letterSpacing: [],
    lineHeight: [],
    listStylePosition: [],
    listStyleType: [],
    margin: [],
    maxHeight: [],
    maxWidth: [],
    minHeight: [],
    minWidth: [],
    objectFit: [],
    objectPosition: [],
    opacity: ['hover', 'focus', 'disabled'],
    order: [],
    outline: ['focus'],
    overflow: [],
    padding: [],
    placeholderColor: ['focus'],
    pointerEvents: [],
    position: [],
    resize: [],
    stroke: [],
    strokeWidth: [],
    tableLayout: [],
    textAlign: [],
    textColor: ['hover', 'focus', 'disabled'],
    textDecoration: ['hover', 'focus', 'disabled'],
    textTransform: [],
    userSelect: [],
    verticalAlign: [],
    visibility: [],
    whitespace: [],
    width: [],
    wordBreak: [],
    zIndex: [],
    gap: [],
    gridAutoFlow: [],
    gridTemplateColumns: [],
    gridColumn: [],
    gridColumnStart: [],
    gridColumnEnd: [],
    gridTemplateRows: [],
    gridRow: [],
    gridRowStart: [],
    gridRowEnd: [],
    transform: [],
    transformOrigin: [],
    scale: ['hover', 'focus', 'disabled'],
    rotate: ['hover', 'focus', 'disabled'],
    translate: ['hover', 'focus', 'disabled'],
    skew: ['hover', 'focus', 'disabled'],
    transitionProperty: [],
    transitionTimingFunction: [],
    transitionDuration: [],
  },
  theme: {
    screens: {
      'lg': '760px',
      'dark': {'raw': '(prefers-color-scheme: dark)'},
    },
    extend: {
      fontFamily: {
        sans: ['Inter', ...defaultTheme.fontFamily.sans],
        serif: ['IBM Plex Serif', ...defaultTheme.fontFamily.serif],
        mono: ['IBM Plex Mono', ...defaultTheme.fontFamily.mono]
      },
    },
  },
}
